import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    width: "100%",
    flex: 1,
    backgroundColor: "#020617",
    position: "relative"
  },
  header: {
    backgroundColor: "#020617",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
  },
  statusBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  time: {
    fontSize: 18,
    fontWeight: "600",
  },
  statusInfo: {
    fontSize: 14,
    fontWeight: "500",
  },
  headerStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  streakBadge: {
    backgroundColor: "#f87171",
    borderRadius: 8,
    width: 48,
    height: 32,
    borderBottomWidth: 2,
    borderBottomColor: "#dc2626",
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  emoji: {
    fontSize: 30,
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ea580c",
  },
  gemIcon: {
    width: 28,
    height: 28,
    backgroundColor: "#60a5fa",
    borderRadius: 8,
    borderBottomWidth: 2,
    borderBottomColor: "#3b82f6",
  },
  plusButton: {
    backgroundColor: "#3b82f6",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
  },
  plusText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  unitHeader: {
    backgroundColor: "#020617",
    paddingHorizontal: 24,
    paddingVertical: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    alignItems: "center",
  },
  unitSubHeader: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
  },

  livesContainer: {
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: "#EC4899",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  livesIcon: {
    fontSize: 18,
  },
  livesText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  unitBack: {
    color: "white",
    fontSize: 4,
  },
  unitTitle: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 4,
  },
  unitSubtitle: {
    color: "white",
    fontSize: 16,
  },
  guideButton: {
    backgroundColor: "#d8b4fe",
    borderRadius: 16,
    padding: 12,
  },
  guideIcon: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  guideGrid: {
    flexDirection: "column",
    gap: 2,
  },
  guideRow: {
    flexDirection: "row",
    gap: 2,
  },
  guideDot: {
    width: 6,
    height: 6,
    backgroundColor: "white",
    borderRadius: 2,
  },
  scrollView: {
    flex: 1,
  },
  progressPath: {
    alignItems: "center",
    paddingVertical: 32,
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  levelContainer: {
    width: "100%",
    gap: 20,
    // marginVertical: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  levelLeft: {
    alignSelf: "flex-start",
    marginLeft: 16,
  },
  levelRight: {
    alignSelf: "flex-end",
    marginRight: 32,
  },
  levelBox: {
    width: "20%", // ± 4 item per baris (100 / 4 = 25%), dikurangi gap
    aspectRatio: 1,
    height: 70,
    backgroundColor: "#fde047",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 10,
    borderBottomColor: "#ca8a04",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  levelPressed: {
    transform: [{ scale: 0.9 }],
  },
  levelText: {
    fontSize: 24,
    fontFamily: "Poppins-Regular",
    fontWeight: 900,
  },
  chestLevel: {
    width: 80,
    height: 80,
    backgroundColor: "#fbbf24",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 4,
    borderBottomColor: "#b45309",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    position: "relative",
  },
  chestTop: {
    width: 56,
    height: 12,
    backgroundColor: "#d97706",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    position: "absolute",
    top: 8,
  },
  chestBody: {
    width: 40,
    height: 40,
    backgroundColor: "#b45309",
    borderRadius: 4,
    marginTop: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  chestLock: {
    width: 12,
    height: 16,
    backgroundColor: "#78350f",
    borderRadius: 2,
  },
  bottomNav: {
    // position: 'absolute',
    // bottom: 0,
    // left: 0,
    // right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#020617",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  navItem: {
    alignItems: "center",
    position: "relative",
  },
  navItemInactive: {
    opacity: 0.6,
  },
  homeIcon: {
    width: 40,
    height: 40,
    backgroundColor: "#dbeafe",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  homeIconInner: {
    width: 24,
    height: 20,
    backgroundColor: "#fb923c",
    borderRadius: 4,
    borderBottomWidth: 2,
    borderBottomColor: "#f97316",
  },
  navEmoji: {
    fontSize: 30,
  },
  notificationDot: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    backgroundColor: "#ef4444",
    borderRadius: 4,
  },
  menuDots: {
    flexDirection: "column",
    gap: 4,
    alignItems: "center",
  },
  menuDot: {
    width: 4,
    height: 4,
    backgroundColor: "#c084fc",
    borderRadius: 2,
  },
});

export default styles;
