import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000410" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  greeting: { color: "#fff", fontSize: 20, fontFamily: "Poppins-Bold" },
  subGreeting: { color: "#9ca3af", fontSize: 12 },
  headerStat: { flexDirection: "row", gap: 12, alignItems: "center" },
  statItem: { alignItems: "center", marginLeft: 8 },
  statText: { color: "#fff", fontSize: 12 },
  card: {
    backgroundColor: "#0f1724",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  cardTitle: { color: "#fff", fontSize: 16, fontFamily: "Poppins-Bold" },
  cardSub: { color: "#9ca3af", fontSize: 13 },
  progressBarBg: {
    height: 8,
    backgroundColor: "#111827",
    borderRadius: 8,
    marginTop: 8,
    overflow: "hidden",
  },
  progressBarFill: {
    height: 8,
    backgroundColor: "#facc15",
  },
  continueBtn: {
    backgroundColor: "#facc15",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginLeft: 12,
  },
  continueText: { color: "#121212", fontWeight: "700" },
  sectionTitle: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Poppins-Bold",
    marginBottom: 8,
  },
  questRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  questTitle: { color: "#fff" },
  questReward: { color: "#9ca3af", fontSize: 12 },
  questBtn: {
    backgroundColor: "#facc15",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 4,
  },
  questBtnText: { color: "#121212", fontWeight: "700" },
  primaryBtn: {
    backgroundColor: "#facc15",
    padding: 10,
    borderRadius: 4,
    marginTop: 12,
  },
  primaryBtnText: { color: "#121212", fontWeight: "700" },
  ghostBtn: {
    borderColor: "#ccc",
    borderWidth: 1,
    padding: 10,
    borderRadius: 4,
    marginLeft: 8,
    marginTop: 12,
  },
  ghostBtnText: { color: "#fff" },
  choiceBtn: {
    backgroundColor: "#0b1220",
    padding: 10,
    borderRadius: 4,
    marginVertical: 6,
  },
  choiceSelected: { borderWidth: 1, borderColor: "#facc15" },
  choiceText: { color: "#fff" },
  correctText: { color: "#4ade80", marginTop: 8 },
  wrongText: { color: "#fb7185", marginTop: 8 },
  leaderIdx: {
    color: "#facc15",
    width: 28,
    textAlign: "center",
    fontWeight: "700",
  },
  leaderName: { color: "#fff" },
  leaderXp: { color: "#9ca3af" },
  smallText: { color: "#9ca3af", fontSize: 12 },
  courseCard: {
    backgroundColor: "#071427",
    padding: 12,
    borderRadius: 10,
    marginRight: 12,
    width: 200,
  },
  courseTitle: { color: "#fff", fontWeight: "700" },
  courseLevel: { color: "#9ca3af", fontSize: 12, marginBottom: 8 },
  announcement: {
    backgroundColor: "#0b1220",
    padding: 10,
    borderRadius: 10,
    marginBottom: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  announcementText: { color: "#fff", marginLeft: 8 },
  mascotCard: { backgroundColor: "#07162a" },
});

export default styles;